constant = {
    "SomethingWentWrong": "Something went wrong!",
    "NoJobs": "No jobs to display!",
    "SuccessJobCreation": "Job creation successful!",
    "BadRequest": "Bad request!",
    "UpdateFail": "Update failed!",
    "JobNotFound": "Job not found",
    "JobNotFoundMsg": "No job for given ID!",
    "SuccessJobUpdate": "Job update successful!",
    "JobDone": "DONE",
    "UserCreationSuccess": "User creation successful!",
    "UseLoginSuccess": "Login successful!",
    "IncorrectCredentials": "Incorrect Credentials!",
    "EmailMissing": "Email address missing!",
    "LogoutSuccess": "Logout successful!",
    "LogoutFailed": "Logout failed!",
}
